export const users = [
  {
    callTag: "Dinitha W.",
    firstname: "Dinitha",
    lastname: "Wijewardhana",
    gender: "male",
    status: "online",
    languages: ["French", "Portuguese"],
    lookingFor: {
      gender: "female",
      ageRange: {
        minAge: 20,
        maxAge: 30,
      },
      height: {
        minHeight: 6.2,
        maxHeight: 7.0,
      },
    },
    email: "dini2040gh@gmail.com",
    dob: "1999-08-09",
    age: 19,
    country: "India",
    occupation: "Driver",
    height: 6.2,
    maritalStatus: "single",
    educationLevel: "graduate",
    monthlyIncome: "between Rs.25,000 & Rs.50,000",
    hasChildren: false,
    religion: "Buddhist",
    ethnicity: "Sinhalese",
    profilePhoto: "dinesh.jpg",
    password: "dinitha123",
    passwordConfirm: "dinitha123",
    userDescription:
      "Hello I'm dinitha from Sri Lanka. Feel free to send me a message. I won't bite. See you all",
  },
  {
    callTag: "Jennifer H.",
    gender: "female",
    country: "India",
    languages: ["Bengali", "Russian"],
    email: "creepySandra@sky.com",
    occupation: "Astronomer",
    height: 5.6,
    maritalStatus: "married",
    educationLevel: "bachelor",
    monthlyIncome: "between Rs.25,000 & Rs.50,000",
    hasChildren: false,
    religion: "Spiritual",
    ethnicity: "welsh",
    profilePhoto: "./img/monica.jpg",
    profileDescription:
      "Web junkie. Analyst. Infuriatingly humble introvert. Food nerd. Lifelong  music fanatic. Coffee lover.",
    movies: ["Comedy", "Drama"],
    music: ["HipHop", "Pop"],
    politics: "Conservative",
    socialMedia: ["Twitter", "Facebook"],
    sports: ["Basketball", "Soccer", "Hockey"],

    userDescription: "Some random description",
    lookingFor: {
      gender: "male",
      ageRange: {
        minAge: 15,
        maxAge: 20,
      },
      height: {
        minHeight: 1.2,
        maxHeight: 3.4,
      },
    },
  },
  {
    firstname: "Robin",
    lastname: "Smith",
    gender: "male",
    languages: ["Indonesian", "Russian"],
    email: "inquisitiveMiguel@yahoo.co.uk",
    occupation: "Chef",
    height: 6.1,
    country: "India",
    maritalStatus: "complicated",
    educationLevel: "bachelor",
    monthlyIncome: "between Rs.25,000 & Rs.50,000",
    hasChildren: false,
    religion: "Christian",
    ethnicity: "african",
    profilePhoto: "./img/erlich.jpg",
    profileDescription:
      "Avid web maven. Food practitioner. Gamer. Twitter fanatic. Pop culture scholar. Zombie evangelist.",
    movies: ["Horror", "Comedy"],
    music: ["HipHop", "Rock"],
    politics: "Moderate",
    socialMedia: ["Reddit", "Youtube"],
    sports: ["Baseball", "Football"],
    userDescription: "Some random description",
    lookingFor: {
      gender: "male",
      ageRange: {
        minAge: 15,
        maxAge: 20,
      },
      height: {
        minHeight: 1.2,
        maxHeight: 3.4,
      },
    },
  },
  {
    firstname: "Jared",
    lastname: "Rodriguez",
    gender: "male",
    languages: ["Arabic", "Russian"],
    email: "shyMelinda@yahoo.fr",
    occupation: "Architect",
    height: [10, 2],
    maritalStatus: "complicated",
    country: "India",
    educationLevel: "graduate",
    monthlyIncome: "between Rs.25,000 & Rs.50,000",
    hasChildren: false,
    religion: "Hindu",
    ethnicity: "african",
    profilePhoto: "./img/jared.jpg",
    profileDescription:
      "Bacon enthusiast. Falls down a lot. Freelance socialMedia fan. Infuriatingly humble introvert.",
    movies: ["Action", "Adventure", "Drama"],
    music: ["Latin", "Rock", "HipHop"],
    politics: "Conservative",
    socialMedia: ["Twitter", "TikTok", "Youtube"],
    sports: ["Hockey", "Football", "Basketball"],
    userDescription: "Some random description",
    lookingFor: {
      gender: "male",
      ageRange: {
        minAge: 15,
        maxAge: 20,
      },
      height: {
        minHeight: 1.2,
        maxHeight: 3.4,
      },
    },
  },
  {
    firstname: "Richard",
    lastname: "Cantrell",
    gender: "male",
    languages: ["Hindi", "Arabic"],
    email: "gloriousBrenda14@facebook.com",
    country: "India",
    occupation: "Doctor",
    height: 4.2,
    maritalStatus: "married",
    educationLevel: "highschool",
    monthlyIncome: "between Rs.25,000 & Rs.50,000",
    hasChildren: false,
    religion: "Hindu",
    ethnicity: "arab",
    profilePhoto: "./img/richard.jpg",
    profileDescription:
      "Pop culture junkie. Tv buff. Reader. Friendly travel expert. Incurable twitteraholic. socialMedia ninja. Coffee enthusiast. Internet specialist.",
    movies: ["Adventure", "Comedy", "Drama"],
    music: ["Pop", "Rock"],
    politics: "Liberal",
    socialMedia: ["Instagram", "Youtube"],
    sports: ["Baseball", "Football"],
    userDescription: "Some random description",
    lookingFor: {
      gender: "male",
      ageRange: {
        minAge: 15,
        maxAge: 20,
      },
      height: {
        minHeight: 1.2,
        maxHeight: 3.4,
      },
    },
  },
];
